require File.expand_path("../lib/nginxtra/version.rb", __FILE__)

def system_exec(cmd)
  puts "Executing: #{cmd}"
  puts %x[#{cmd}]
end

module Nginxtra
  class Gem
    class << self
      def dependencies
        { :thor => "~> 0.16.0" }
      end

      def to_s
        "nginxtra-#{Nginxtra::Version}.gem"
      end
    end
  end
end

task :default => :install

task :advance_version do
  puts "Generating version.rb"
  parts = Nginxtra::Version.to_s.split "."
  parts[-1] = parts[-1].to_i + 1
  next_version = parts.join "."
  File.write File.expand_path("../lib/nginxtra/version.rb", __FILE__), %{module Nginxtra
  class Version
    class << self
      def to_s
        "#{next_version}"
      end
    end
  end
end
}
  load File.expand_path("../lib/nginxtra/version.rb", __FILE__)
  Rake::Task[:generate].execute
end

task :generate do
  puts "Generating nginxtra.gemspec"
  File.write File.expand_path("../nginxtra.gemspec", __FILE__), %{# Note: This gemspec generated by the Rakefile
require "rubygems/package_task"

Gem::Specification.new do |s|
  s.name           = "nginxtra"
  s.version        = "#{Nginxtra::Version}"
  s.summary        = "Wrapper of nginx for easy install and use."
  s.description    = "This gem is intended to provide an easy to use configuration file that will automatically be used to compile nginx and configure the configuration."
  s.author         = "Mike Virata-Stone"
  s.email          = "reasonnumber@gmail.com"
  s.files          = FileList["bin/**/*", "lib/**/*", "templates/**/*", "vendor/**/*"]
  s.require_path   = "lib"
  s.bindir         = "bin"
  s.executables    = ["nginxtra", "nginxtra_rails"]
  s.homepage       = "http://reasonnumber.com/nginxtra"
  s.add_dependency "thor", "#{Nginxtra::Gem.dependencies[:thor]}"
end
}

  puts "Generating bin/nginxtra"
  File.write File.expand_path("../bin/nginxtra", __FILE__), %{#!/usr/bin/env ruby
require "rubygems"
gem "nginxtra", "= #{Nginxtra::Version}"
gem "thor", "#{Nginxtra::Gem.dependencies[:thor]}"
require "nginxtra"
Nginxtra::CLI.start
}

  puts "Generating bin/nginxtra_rails"
  File.write File.expand_path("../bin/nginxtra_rails", __FILE__), %{#!/usr/bin/env ruby
require "rubygems"
gem "nginxtra", "= #{Nginxtra::Version}"
gem "thor", "#{Nginxtra::Gem.dependencies[:thor]}"
require "nginxtra"
Nginxtra::Rails::CLI.start
}
end

task :build => :generate do
  puts "Building nginxtra"
  system_exec "gem build nginxtra.gemspec"
end

task :install => :build do
  puts "Installing nginxtra"
  system_exec "gem install --no-ri --no-rdoc #{Nginxtra::Gem}"
end

task :tag do
  puts "Tagging nginxtra"
  system_exec "git tag -a #{Nginxtra::Version} -m 'Version #{Nginxtra::Version}' && git push --tags"
end

task :push => :build do
  puts "Pushing nginxtra"
  system_exec "gem push #{Nginxtra::Gem}"
end
